### ISSUE TITLE
[Tracking] [scaffolding-chef-inspec] Builds fail in Windows docker studio due to InSpec Windows packaging shananigans

### ISSUE THREAD

**Issue by echohack** [chef/effortless#85]
This is a tracking issue. No fix may be required in this repo, but further investigation is warrented.

To repro: enter a Windows docker studio and build any package that uses `scaffolding-chef-inspec` on Windows

```
hab studio enter -D
build
```

## Sample Output

```
Traceback (most recent call last):
        21: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/bin/inspec:23:in `<main>'
        20: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/bin/inspec:23:in `load'
        19: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/gems/2.6.0/gems/inspec-3.7.11/bin/inspec:10:in `<top (required)>'
        18: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/gems/2.6.0/gems/inspec-3.7.11/bin/inspec:10:in `require_relative'
        17: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/gems/2.6.0/gems/inspec-3.7.11/lib/inspec.rb:12:in `<top (required)>'
        16: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        15: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        14: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/gems/2.6.0/gems/inspec-3.7.11/lib/inspec/profile.rb:17:in `<top (required)>'
        13: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        12: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/gems/2.6.0/gems/inspec-3.7.11/lib/inspec/profile_context.rb:8:in `<top (required)>'
        10: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         9: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         8: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/gems/2.6.0/gems/inspec-3.7.11/lib/inspec/control_eval_context.rb:4:in `<top (required)>'
         7: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/gems/2.6.0/gems/inspec-3.7.11/lib/inspec/dsl.rb:6:in `<top (required)>'
         4: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/gems/2.6.0/gems/inspec-3.7.11/lib/inspec/plugin/v2.rb:30:in `<top (required)>'
         1: from C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/hab/pkgs/stuartpreston/inspec/3.7.11/20190328052257/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': Invalid argument @ rb_readlink - C:/src (Errno::EINVAL)
   effortless-a2-profile-test: Clean the cache


    Directory: C:\hab\cache\src


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        7/23/2019  10:20 AM                effortless-a2-profile-test-0.1.0
   effortless-a2-profile-test: Setting env:LIB=
   effortless-a2-profile-test: Setting env:INCLUDE=
   effortless-a2-profile-test: Preparing to build
   effortless-a2-profile-test: Building

Cannot fetch compliance://admin/stig-windowsserver2016-i-missioncriticalpublic because your compliance token has not been
configured.

Please login using

    inspec compliance login https://your_compliance_server --user admin --insecure --token 'PASTE TOKEN HERE'
   effortless-a2-profile-test: Installing
Copy-Item : Cannot find path 'C:\hab\cache\src\effortless-a2-profile-test-0.1.0\effortless-a2-profile-test-0.1.0.tar.gz' because it does not exist.
At C:\hab\pkgs\echohack\scaffolding-chef-inspec\0.10.0\20190723101649\lib\scaffolding.ps1:109 char:5
+     Copy-Item "$HAB_CACHE_SRC_PATH/$pkg_dirname/$pkg_name-$pkg_versio ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\hab\cache\sr...st-0.1.0.tar.gz:String) [Copy-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

**Comment by TheLunaticScripter** [comment]
I think this is fixed with release `0.13.0`
